spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itprom_demo?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: tyoma199814
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      org:
        hibernate:
          envers:
            store_data_at_delete: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:/data.sql