spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/itprom_demo
    username: postgres
    password: tyoma199814
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: true
    properties:
      org:
        hibernate:
          envers:
            store_data_at_delete: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:/data.sql